### ISSUE TITLE
card-thumb

### ISSUE THREAD

**Issue by tricodando** [tricodando/card-html-css#1]
![card-html-css](https://user-images.githubusercontent.com/85141942/233807078-56be2105-d076-4047-b53a-51c7619a1f07.png)

**Comment by reuelcaetano** [comment]
![Screenshot from 2024-09-13 17-05-27](https://github.com/user-attachments/assets/5c9630c4-4cb7-4c01-9e48-3d0f29849101)

**Comment by tricodando** [comment]
![Screenshot from 2024-09-13 17-05-27](https://github.com/user-attachments/assets/58d2e004-f6eb-463a-b80f-25ffc6f85320)
